Repository CS2103JAN2018-W11-B3/main, pull requests merged in 2018-04, with the labels that each got.

#84 Report: add ViewReport
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/ViewReportCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/ViewReportCommandParser.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/ReadOnlyAddressBook.java
  src/main/java/seedu/address/model/report/Proportion.java
  src/main/java/seedu/address/model/report/Report.java
  src/main/java/seedu/address/model/report/UniqueReportList.java
  src/main/java/seedu/address/model/report/exceptions/DuplicateReportException.java
  src/main/java/seedu/address/model/report/exceptions/ReportNotFoundException.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReportPanel.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/ReportCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
Labels: type.task

#82 Autocorrect and Autocomplete
  docs/UserGuide.adoc
  src/main/java/seedu/address/commons/events/ui/CommandCorrectedEvent.java
  src/main/java/seedu/address/logic/CommandCorrection.java
  src/main/java/seedu/address/ui/CommandBox.java
  src/main/java/seedu/address/ui/ResultDisplay.java
Labels: Type: Feature

#89 Feature: FacebookLoginCommand to connect the addressbook to a fb account
  src/main/java/seedu/address/logic/commands/FacebookLoginCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
Labels: Type: Feature, type.story

#91 Doc: update ug for facebooklogin
  docs/UserGuide.adoc
Labels: Type: Doc

#98 Add bar chart to the report, modify theme color scheme
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/report/Proportion.java
  src/main/java/seedu/address/model/report/Report.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/ReportPanel.java
  src/main/java/seedu/address/ui/UiStyle.java
  src/main/resources/view/MorningTheme.css
  src/main/resources/view/ReportPanel.fxml
Labels: type.task

#103 Update user guide W12
  README.adoc
  docs/UserGuide.adoc
  docs/images/Find.png
  docs/images/addtag.png
  docs/images/barchart.png
  docs/images/deletetag.png
  docs/images/history.png
  docs/images/logo
  docs/images/piechart.png
  docs/images/savereport.png
  docs/images/viewreport.png
Labels: type.task

#139 Fix Storage for Interview
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/AddInterviewCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/interview/Date.java
  src/main/java/seedu/address/model/interview/Interview.java
  src/main/java/seedu/address/storage/XmlAdaptedInterview.java
  src/main/java/seedu/address/storage/XmlSerializableAddressBook.java
Labels: Type: Bug, type.task

#149 Update dev guide w12
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/anh2111.adoc
  src/main/resources/view/MorningTheme.css
Labels: type.task

#147 Feature: facebook authorization and facebook post
  build.gradle
  src/main/java/seedu/address/commons/events/ui/BrowserUrlChangedEvent.java
  src/main/java/seedu/address/logic/commands/FacebookLoginCommand.java
  src/main/java/seedu/address/logic/commands/FacebookPostCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FacebookPostCommandParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/resources/facebook4j.properties
Labels: Type: Feature, type.epic, type.task

#150 Doc: Add portfolio
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/team/tiny767.adoc
Labels: Type: Doc

#151 update UGDG
  docs/UserGuide.adoc
Labels: Type: Doc

#170 Facebook feature update
  src/main/java/seedu/address/commons/events/ui/BrowserUrlChangedEvent.java
  src/main/java/seedu/address/commons/events/ui/ToggleFacebookPanelEvent.java
  src/main/java/seedu/address/logic/commands/FacebookLoginCommand.java
  src/main/java/seedu/address/logic/commands/FacebookPostCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/ui/BrowserPanel.java
  src/main/java/seedu/address/ui/FacebookPanel.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/FacebookPanel.fxml
  src/main/resources/view/LightTheme.css
  src/test/java/seedu/address/logic/commands/FacebookLoginCommandTest.java
  src/test/java/seedu/address/logic/commands/FacebookPostCommandTest.java
  src/test/java/seedu/address/logic/parser/FacebookPostCommandParserTest.java
Labels: Type: Bug, Type: Enhancement

#172 Add more tests (remark command, its parser, fblogin system test)
  src/main/java/seedu/address/logic/commands/FacebookLoginCommand.java
  src/main/java/seedu/address/logic/commands/RemarkCommand.java
  src/main/java/seedu/address/logic/commands/ThemeCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/java/seedu/address/ui/UiTheme.java
  src/test/java/seedu/address/logic/commands/RemarkCommandTest.java
  src/test/java/seedu/address/logic/parser/RemarkCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ThemeCommandParserTest.java
  src/test/java/systemtests/FacebookLoginCommandSystemTest.java
  src/test/java/systemtests/FacebookPostCommandSystemTest.java
Labels: Test

#182 W12 update UG DG
  docs/DeveloperGuide.adoc
  docs/UserGuide.adoc
  docs/images/FacebookAppCreated.png
  docs/images/FbSequenceDiagram.png
  src/main/java/seedu/address/logic/commands/FacebookLoginCommand.java
  src/main/resources/facebook4j.properties
Labels: Type: Doc
